[versions]
kotlin = "2.0.0"
compose = "1.7.0-alpha01"
agp = "8.5.1"
androidx-activityCompose = "1.9.1"
androidx-uiTest = "1.6.8"
maven-publish = "0.29.0"
filekit-compose = "0.7.0"
kpermission = "1.0.2"
search-drop-down = "2.0.6"
compose-ritch-editor = "1.0.0-rc05"
color-picker = "1.1.1"
google-fonts = "1.6.8"
room = "2.7.0-alpha05"
ksp = "2.0.0-1.0.24"
sqlite = "2.5.0-alpha05"

coil = "3.0.0-alpha09"
napier = "2.7.1"
kotlinx-coroutines = "1.8.1"
ktor = "3.0.0-wasm2"
kotlinx-serialization = "1.7.1"

[libraries]
androidx-activityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-testManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "androidx-uiTest" }
androidx-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "androidx-uiTest" }
coil = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil" }
coil-network-ktor = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktor-client-curl = { module = "io.ktor:ktor-client-curl", version.ref = "ktor" }
ktor-client-winhttp = { module = "io.ktor:ktor-client-winhttp", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

filekit-compose = { module = "io.github.vinceglb:filekit-compose", version.ref = "filekit-compose" }
kpermissions = { module = "io.github.the-best-is-best:KPermissions", version.ref = "kpermission" }
search-drop-down = { module = "io.github.the-best-is-best:ComposeSearchableDropdown", version.ref = "search-drop-down" }
compose-rich-editor = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "compose-ritch-editor" }
color-picker = { module = "com.github.skydoves:colorpicker-compose", version.ref = "color-picker" }
google-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "google-fonts" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-runtime-android = { module = "androidx.room:room-runtime-android", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }



[plugins]
multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
maven-publish = {id = "com.vanniktech.maven.publish" , version.ref = "maven-publish"}
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
